### ISSUE TITLE
Image fails to build with alpine/Dockfile

### ISSUE THREAD

**Issue by ttasovac** [hackmdio/codimd-container#20]
I'm trying to build the codimd image with alpine/Dockfile, but the build fails. 

I'm getting some node-related errors (see below), which is way above my paygrade. Does anybody know how to fix this?

```
$ npm run-script build && node release
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1549117944179-0.35038082300109297/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> codemirror@5.41.1 build /usr/local/share/.cache/yarn/v4/.tmp/494d4cd821398a8aa6f314056acc7b33.490cdc903e06895354691e7a06b84203b3be4a6e.prepare
> rollup -c


src/codemirror.js → lib/codemirror.js...
(!) Circular dependency: src/display/highlight_worker.js -> src/display/operations.js -> src/display/scrollbars.js -> src/display/scrolling.js -> src/display/highlight_worker.js
(!) Circular dependency: src/display/update_display.js -> src/display/highlight_worker.js -> src/display/operations.js -> src/display/scrollbars.js -> src/display/scrolling.js -> src/display/line_numbers.js -> src/display/update_display.js
(!) Circular dependency: src/display/update_display.js -> src/display/highlight_worker.js -> src/display/operations.js -> src/display/scrollbars.js -> src/display/scrolling.js -> src/display/update_display.js
(!) Circular dependency: src/display/update_display.js -> src/display/highlight_worker.js -> src/display/operations.js -> src/display/update_display.js
(!) Circular dependency: src/edit/CodeMirror.js -> src/model/Doc.js -> src/edit/CodeMirror.js
created lib/codemirror.js in 1.3s
WARN: Non-strict equality against boolean: == false [lib/codemirror.js:1210,61]
WARN: Non-strict equality against boolean: != false [addon/comment/comment.js:107,55]
WARN: Non-strict equality against boolean: != false [addon/comment/comment.js:120,10]
WARN: Non-strict equality against boolean: == false [mode/javascript/javascript.js:443,13]
WARN: Non-strict equality against boolean: == false [mode/javascript/javascript.js:444,15]
WARN: Non-strict equality against boolean: != false [mode/javascript/javascript.js:860,55]
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "js-url > grunt-contrib-jshint@2.0.0" has unmet peer dependency "grunt@>=0.4.0".
[5/5] Building fresh packages...
error /codimd/node_modules/@mlink/scrypt: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /codimd/node_modules/@mlink/scrypt
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.15.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/codimd/node_modules/@mlink/scrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/8.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.15.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/codimd/node_modules/@mlink/scrypt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/codimd/node_modules/@mlink/scrypt/build'
  SOLINK_MODULE(target) Release/obj.target/copied_files.node
  COPY Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  AR(target) Release/obj.target/scrypt_wrapper.a
  COPY Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.1/lib/crypto/crypto_scrypt.o
In file included from ../scrypt/scrypt-1.2.1/lib/crypto/crypto_scrypt.c:29:0:
../scrypt/scrypt-1.2.1/scrypt_platform.h:7:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
make: *** [scrypt_lib.target.mk:119: Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.1/lib/crypto/crypto_scrypt.o] Error 1
make: Leaving directory '/codimd/node_modules/@mlink/scrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.10.0-957.1.3.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /codimd/node_modules/@mlink/scrypt
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'app' failed to build: The command '/bin/sh -c apk add --no-cache --virtual .dep build-base python git jq bash &&     git clone --depth 1 --branch "$VERSION" "$CODIMD_REPOSITORY" /codimd &&     cd /codimd &&     git log --pretty=format:'%ad %h %d' --abbrev-commit --date=short -1 && echo &&     git rev-parse HEAD > /tmp/gitref &&     rm -rf /codimd/.git &&     mkdir /codimd/.git &&     mv /tmp/gitref /codimd/.git/HEAD &&     jq ".repository.url = \"${CODIMD_REPOSITORY}\"" /codimd/package.json > /codimd/package.new.json &&     mv /codimd/package.new.json /codimd/package.json &&     rm -f /codimd/config.json && ln -s /files/config.json /codimd/config.json &&     rm -f /codimd/.sequelizerc && ln -s /files/.sequelizerc /codimd/.sequelizerc &&     yarn install --pure-lockfile &&     yarn install --production=false --pure-lockfile &&     npm run build &&     yarn install &&     yarn cache clean &&     apk del .dep &&     adduser -u 10000 -h /codimd/ -D -S codimd &&     chown -R codimd /codimd/' returned a non-zero code: 1
```

**Comment by 0141KoppePan** [comment]
mlink/scrypt need openssl-dev.

See: See [ml1nk/node-scrypt #6](https://github.com/ml1nk/node-scrypt/issues/6)

``` diff
--- a/alpine/Dockerfile
+++ b/alpine/Dockerfile
@@ -50,7 +50,7 @@ RUN set -ex; \
 COPY resources/config.json resources/.sequelizerc /files/

 # Install all dependencies and build project
-RUN apk add --no-cache --virtual .dep build-base python git jq bash && \
+RUN apk add --no-cache --virtual .dep build-base python git jq bash openssl-dev && \
     # Clone the source
     git clone --depth 1 --branch "$VERSION" "$CODIMD_REPOSITORY" /codimd && \
     # Print the cloned version and clean up git files
```

**Comment by SISheogorath** [comment]
Should be fixed with https://github.com/hackmdio/codimd-container/commit/393466f5ca6f1d4ae3f6103f6887b011900b51b4

Thanks for the hints!
